### ISSUE TITLE
Issue with running it.

### ISSUE THREAD

**Issue by rmulr** [filipefilardi/whatsapp-broadcast-crawler#1]
```
 ./broadcast.py
Traceback (most recent call last):
  File "./broadcast.py", line 3, in <module>
    import selenium.webdriver.support.ui as ui
ImportError: No module named selenium.webdriver.support.ui
```

```
[root@CentOS-74-64-minimal ~]# pip install -U selenium
Requirement already up-to-date: selenium in /opt/miniconda3/lib/python3.6/site-packages

```

**Comment by filipefilardi** [comment]
I'm almost sure your error is caused by not have installed geckodriver. Can you double check section 1.3 drivers in [selenium documentation](http://selenium-python.readthedocs.io/installation.html).

`pip install selenium ` is not enough to use selenium. You must install a webdriver and for our case, geckdriver (Mozilla). I recommend read the section 1.3 mentioned and then [download driver here](https://github.com/mozilla/geckodriver/releases).

**Comment by rmulr** [comment]
Solved it. i was using the wrong geckodriver. Thanks for your kind help
